"""Update video model to use binary storage

Revision ID: d9dc2ffdce86
Revises: ce9d71ffc4e5
Create Date: 2025-04-05 11:17:32.869790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dc2ffdce86'
down_revision: Union[str, None] = 'ce9d71ffc4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
